### ISSUE TITLE
Getting an optional

### ISSUE THREAD

**Issue by wimmelstein** [Klimenka/BookShop#1]
Hi Nadia,

When you do a findFirst(), the return type is Optional<T>; you may get a result, or not. If you just do get() like in your following fragment:

Book book = bookByTitle
                .filter(b -> b.getTitle().contentEquals(title))
                .findAny()
                .get();

and the title is not there, then you will get a NoSuchElementException. I don't think that is what you want. So, it's best to orElse() or orElseThrow(). 

Kind regards, 
Wim Wiltenburg

**Comment by Klimenka** [comment]
Thank you
